### ISSUE TITLE
Support git worktrees

### ISSUE THREAD

**Issue by picnoir** [NinjaTrappeur/my-repo-pins#11]
See https://github.com/NinjaTrappeur/my-repo-pins/issues/7#issuecomment-1186525998

**Comment by picnoir** [comment]
What do we'd like to do here?

1. Detect the git worktrees living in the code-root but out of their main worktrees and adding them to the project list.
2. Adding all the worktrees to the projects list, even if they live under the main worktree directory.

While I'm fine with adding 1 to my-repo-pins, I feel like implementing 2 is out of scope.

In order to implement 2, you'd have to start parsing the `.git` directory to find out whether or not there are some worktrees and parse the `.git/worktrees/(...)/gitdir` directories to find out their real locations. These locations could be **outside** of the code-root, hence breaking some assumptions my-repo-pins makes down the line.

I personally think that parsing the `.git` dir falls down in the magit scope. Magit already does it, and it does it **really** well in my opinion.

So, instead of poorly re-implementing parts of magit or depending on it, I'd be more inclined to adopt a composition-based approach.

IE. suggesting users to add a command vaguely looking like this in their configuration:

```elisp
(defun my-repo-pins-and-find-worktrees ()
  (interactive)
  (my-repo-pins)
  (magit-worktree))
```

You can then press `g` to find all the living worktrees and jump to them. I think it does compose fairly well.

@m-cat, what do you think? What did you have in mind, feature 1 or feature 2? If you had feature 2 in mind, what do you think about composing my-repo-pins with magit in your user configuration?

**Comment by mrcnski** [comment]
I'm confused about the two options. I may just be tired -- had a long week. And what do you mean by composing with magit? 

I *think* I was thinking about only implementing (1) -- i.e. when encountering any `.git` files indicating a worktree, accept the directory as a project if the main repo is also in the `my-repo-pins` directory.

Alternatively, there could be a configuration option that skips the `git` check and accepts all directories within the structure as valid projects. That would be a quick fix, and might come in handy anyways. (1) seems cleaner for this specific use case, though.

**Comment by mrcnski** [comment]
P.S. I would be happy to tackle this myself, to practice my elisp chops. It would have to wait a few days, though.

**Comment by picnoir** [comment]
> I'm confused about the two options. I may just be tired -- had a long week.

Bad news: it's Wednesday :sweat_smile: 

> I think I was thinking about only implementing (1) -- i.e. when encountering any .git files indicating a worktree, accept the directory as a project if the main repo is also in the my-repo-pins directory.

:+1:  Sounds good.

> Alternatively, there could be a configuration option that skips the git check and accepts all directories within the structure as valid projects. That would be a quick fix, and might come in handy anyways. (1) seems cleaner for this specific use case, though.

Also sounds good as long as it's opt-in.

> P.S. I would be happy to tackle this myself, to practice my elisp chops. It would have to wait a few days, though.

Sure! No rush.

This is my first decently sized elisp project. There are probably some weird non-idiomatic stuff in here, don't take that as state of the art elisp.

Don't hesitate to ping me on Matrix or IRC if you need help on  some specific parts.

**Comment by mrcnski** [comment]
So at first I tried this, based on [this SO answer](https://stackoverflow.com/questions/2180270/check-if-current-directory-is-a-git-repository):

```el
(defun my-repo-pins--is-git-dir (dir)
  "Return non-nil if DIR is a git directory."
  (let ((default-directory dir))
    (string= (shell-command-to-string "git rev-parse --is-inside-work-tree")
        "true\n")))
```

I had a feeling that this might be pretty slow, but it was *really* slow. So I changed it to this:

```el
(defun my-repo-pins--is-git-dir (dir)
  "Return non-nil if DIR is a git directory."
  (file-exists-p (concat dir ".git")))
```

(so the only change is using `file-exists-p` instead of `file-directory-p`). It works like a charm.

If that looks good to you I can raise a PR. I don't think we need to do anything fancy with parsing the `.git` file -- we already weren't validating the `.git` when we were just expecting a directory, and reading the file will probably add a significant slowdown.

**Comment by mrcnski** [comment]
P.S. I'm not pro enough to comment on the elisp quality, but the code is really well-documented and the names are quite descriptive. That's always nice, so thanks!

**Comment by picnoir** [comment]
> I had a feeling that this might be pretty slow, but it was really slow

Yeah, I thought about using git itself as well. This is on the plugin hot path. Spinning up a process for each and every directory is sadly too costly on Unixes :(

It looks good! Please open a PR :)

As a nit, you can maybe "clean" `dir` using `file-name-as-directory` just to be sure it has a trailing slash as expected by the `concat` here. The performance hit is negligible and it'd make everything a bit more fool-proof.

> P.S. I'm not pro enough to comment on the elisp quality, but the code is really well-documented and the names are quite descriptive. That's always nice, so thanks!

Thanks for the kind words :)
