### ISSUE TITLE
Directories created if cloning fails

### ISSUE THREAD

**Issue by andir** [NinjaTrappeur/my-repo-pins#13]
Lets assume you are trying to clone a repository from a git forge that you have previously not checked out. You are typing it into `M-x my-repo-pins` manually and make a typo somewhere. Git cloning will fail but now you've a couple of directories in your root folder that aren't useful.

**Comment by picnoir** [comment]
Currently, `git clone` is creating this empty directory: https://github.com/NinjaTrappeur/h.el/blob/bb8f205bad176357441e6237c5488158d7fc64a2/my-repo-pins.el#L796

I guess we have two options:

1. We manually create the directory before calling git clone. We delete these directories if `git clone` fails. In that case, we'd probably want to keep track of the full list of directories created to delete all of them.
2. We check the remote repository does exist before calling `git clone`. We probably could do that using something along the line of `git ls-remote https://github.com/NinjaTrappeur/my-repo-pin.git -q --exit-code`.

I personally prefer the option 2.

**Comment by andir** [comment]
Yeah, 2. sounds good.
