### ISSUE TITLE
short form clone not working

### ISSUE THREAD

**Issue by brianmcgillion** [NinjaTrappeur/my-repo-pins#21]
I only noticed this issue in the past 2 days (maybe a few weeks since I last synced):

when trying `my-repo-pins` with the short form of a project e.g.  `NinjaTrappeur/my-repo-pins` it drops straight into the Dired buffer at the root defined by `my-repo-pins-code-root` and does not attempt to search for the repo in the default forges.

If I use the long form `https://github.com/NinjaTrappeur/my-repo-pins` it will successfully clone the repo and drop into Dired at the root of the latest cloned repo.

The standard `Jump to project` also works to enter the previously cloned projects.

**Comment by picnoir** [comment]
Thanks for the heads up, I can reproduce.

I half-assed https://github.com/NinjaTrappeur/my-repo-pins/commit/ff7ca8d5343c8ab3f464cc5c0f40879bc02833f8, it's payback time ><

I'll push a fix shortly.

**Comment by picnoir** [comment]
Fixed by https://github.com/NinjaTrappeur/my-repo-pins/commit/47083f9a74dedf5452975ddc65d3334f91449627

Thanks for the heads up Brian. The fix should reach Melpa soon.
