### ISSUE TITLE
The info of packge on Emacs package manager has a incorrect link

### ISSUE THREAD

**Issue by maxxcan** [NinjaTrappeur/my-repo-pins#3]
If you open the info of package on the package manager when you push the link open the "https://github.com/NinjaTrappeur/my-repo-pins.el" address and it's a error. 

The correct address will be "https://github.com/NinjaTrappeur/my-repo-pins"

**Comment by picnoir** [comment]
Good catch.

Thanks a lot for the heads-up!

**Comment by maxxcan** [comment]
you're welcome
