### ISSUE TITLE
Error when trying to open existing repo from URL

### ISSUE THREAD

**Issue by mrcnski** [NinjaTrappeur/my-repo-pins#9]
Found another issue! So I provided `https://github.com/NinjaTrappeur/my-repo-pins` as the input to `my-repo-pins`, but there was an error to the effect of the folder already existing. In which case, it should just open the existing repo - the user shouldn't have to remember whether he already checked out the repo, or not.

Thanks!

**Comment by picnoir** [comment]
Ah, nice! I missed that use case indeed!

**Comment by picnoir** [comment]
Thanks!
